name: Build and Push to ECR

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-2
      ECR_REPOSITORY: actions-test
      ACCOUNT_ID: 320959454024

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show project structure (debug)
        run: ls -R

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION | \
          docker login \
            --username AWS \
            --password-stdin $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

      # =========================
      # Backend
      # =========================
      - name: Build backend image
        run: |
          docker build \
            -f backend/scripts/Dockerfile \
            -t $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:backend-${{ github.sha }} \
            backend

      - name: Push backend image
        run: |
          docker push \
            $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:backend-${{ github.sha }}

      # =========================
      # Frontend
      # =========================
      - name: Build frontend image
        run: |
          docker build \
            -f frontend/scripts/Dockerfile \
            -t $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:frontend-${{ github.sha }} \
            frontend

      - name: Push frontend image
        run: |
          docker push \
            $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:frontend-${{ github.sha }}
