name: List ECR Images (OIDC)

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  list-images:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: us-east-1   # change if needed
      - name: Show existing ECR repos
        run: aws ecr describe-repositories --output table


      - name: List all image tags
        run: |
          aws ecr list-images \
            --repository-name actions-test \
            --query 'imageIds[*].imageTag' \
            --output table
